### ISSUE TITLE
[BUG] Nanolag on save

### ISSUE THREAD

**Issue by ViaEnder** [SBDPlugins/V10Lift#56]
**Describe the bug**
We got many lifts and everytime we edit a lift we get a nano lag, maby if we create more it will be a bigger lag.

**To Reproduce**
Edit or create a new lift

**Spigot version (use /version):**
v 1.16.5

**Plugin version (use /v10lift info), NOT LATEST!!!**
v 0.1.8.30

**Additional context**

**Comment by stijnb1234** [comment]
Will check what's possible. Possibly change it to a saving task or something like that.
