### ISSUE TITLE
[FEATURE] List of all V10Lifts

### ISSUE THREAD

**Issue by JaHollTV** [SBDPlugins/V10Lift#58]
**Is your feature request related to a problem? Please describe.**
It would be awesome to get a List of all v10Lifts that exists on a Server

**Describe the solution you'd like**
/v10lift listAll [page]
-> as user: print 20 lifts per page
-> in console: print all

**Describe alternatives you've considered**
none

**Additional context**
hope you are still active!

**Comment by stijnb1234** [comment]
Good idea. Will add. 👍

**Comment by JaHollTV** [comment]
I look forward for this little update :)

Our Roleplay-Server uses v10lift -- i you fine with it then i will publish more requests in the future

**Comment by JaHollTV** [comment]
Hey there,
anything new :) ?

**Comment by xCraimax** [comment]
You can just type /v10lift edit and then the Autocomplete-Function will show you a list of all the lifts. Maybe thats something, that might help you 😄
