### ISSUE TITLE
[BUG] Offline-Input not working correctly

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#63]
**Describe the bug**
When i place 3 levers in row, set them to offline-inputs for 3 different elevators, everything looks fine. When i enable and disable 1, then its working fine too. But when i enable 2 or more, then i‘ll have to disable them in the same order, as I enabled them. I think this problem is not related to the fact, that they‘re placed in a row, but more to a server-wide problem.

**To Reproduce**
1. Create 2 Elevators
2. place 2 levers somewhere
3. set these 2 levers as the offline-input
4. trigger them
5. Try to disable them in another order, as you turned them on.

**Expected behavior**
The Elevators get en-/disabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/49165798/184501192-1049c8a5-fa1b-4b97-a8f0-3c6f749ee7c5.png)
![image](https://user-images.githubusercontent.com/49165798/184501194-8509e54e-1024-424c-96e8-876f1be75ba2.png)
![image](https://user-images.githubusercontent.com/49165798/184501196-20356901-198e-44e0-8186-4a1ea74d6746.png)
![image](https://user-images.githubusercontent.com/49165798/184501203-85125bea-74ba-47d2-b963-a00ee10181f7.png)

**Spigot version (use /version):**
v1.18.2 // git-Paper-386

**Plugin version (use /v10lift info), NOT LATEST!!!**
v0.7.4.1

**Additional context**

**Comment by stijnb1234** [comment]
Will look into that. I think it's caused by the levers placed in a row.

**Comment by xCraimax** [comment]
Thats what I've got using different X and Y Coordinate for Offline Inputs:
![image](https://user-images.githubusercontent.com/49165798/184508522-a88b80f1-ddd0-4ee3-b0b8-aff631d7d465.png)

(Problem is still there)
