### ISSUE TITLE
[FEATURE] Add the option, to use a button as a dis-/enabler of the elevator (like the offline-lever, but with two different buttons)

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#64]
**Is your feature request related to a problem? Please describe.**
I'm playing on a RolePlay Server and want to create an Emergency-Disable button when something goes wrong. And a system like this would be kind of usefull to it.

**Describe the solution you'd like**
You create an elevator and a button (example: stone button; any should be possible). Then you use a command like "/v10lift disable-button add" and set the button (like in /v10lift input add). This button just disabled the elevator, like an (already existing) Offline-Input, but does only dis- or enable the elevator. Logically, there would be a command to remove such a trigger block.

**Describe alternatives you've considered**
none

**Additional context**

**Comment by stijnb1234** [comment]
Good idea. Will look into that.

**Comment by xCraimax** [comment]
Not sure how this is implemented either.
@stijnb1234 Sorry for the trouble, but could you explain this please?

**Comment by stijnb1234** [comment]
> Not sure how this is implemented either.
> @stijnb1234 Sorry for the trouble, but could you explain this please?

Yeah, I understand. You can just add the button as an offline input, like you would do with the levers. When you press the button, it should toggle the offline state of the elevator. It should also toggle all the levers.
