### ISSUE TITLE
[FEATURE] Multiple offline inputs for one elevator

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#66]
**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
When I create two offline-inputs (both linked to the same elevator)and disable both, then it's disabled. But when I enable only **one out of two**, then it enabled the elevator, ignoring that an offline-input is still enabled.

**Describe alternatives you've considered**
none.

**Additional context**
I wasn't sure if I should put it to bug-issue or feature-request :/

**Comment by stijnb1234** [comment]
It's indeed more a feature request.

**Comment by stijnb1234** [comment]
The best way to implement this, is to toggle all the levers when you toggle one. This makes sure all the levers have the same state.

**Comment by xCraimax** [comment]
The problem with that is, that I can't toggle all the levers on the whole server, everytime I want to toggle one.

**Comment by stijnb1234** [comment]
> The problem with that is, that I can't toggle all the levers on the whole server, everytime I want to toggle one.

Was a note to myself haha, the plugin will then toggle them all for you.
