### ISSUE TITLE
[BUG] Duplicating Carpets

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#68]
**Describe the bug**
You can duplicate carpets, when 2 carpets are connected to each other.

**To Reproduce**
1. Create an Elevator with 2 Carpets (optional:) and 2 blocks below them
2. Create at least 2 floors
3. Start the Elevator

**Expected behavior**
Not duplicating.

**Screenshots**

**Spigot version (use /version):**
git-Paper-283 (MC 1.18.2)

**Plugin version (use /v10lift info), NOT LATEST!!!**
v0.7.4.1

**Additional context**
/

**Comment by stijnb1234** [comment]
Do you have a screenshot of the way you laid your carpets?

**Comment by stijnb1234** [comment]
> Do you have a screenshot of the way you laid your carpets?

@xCraimax ?

**Comment by xCraimax** [comment]
Sure. Sorry for not replying.

(Before pressing a button)
![image](https://github.com/SBDPlugins/V10Lift/assets/49165798/57f18cc4-8d13-46a4-b7a1-b054086f7bcb)

(After pressing a button)
![image](https://github.com/SBDPlugins/V10Lift/assets/49165798/44202e5d-26f2-42cc-96c9-6483f5dc5a9c)
