### ISSUE TITLE
[BUG] Bug with Block States

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#69]
**Describe the bug**
I wasn't sure, if I should put this as a Bug report or a feature request.
When I use a closed/opened (vertical) trapdoor as a rope, then it always returns horizontal on placement.

**To Reproduce**
1. Create a Lift
2. Create a vertical line of vertical/opened trapdoors
3. add two floors
4. use the trapdoors as a rope
5. Start the Lift

**Expected behavior**
A vertical trapdoor (as placed before selecting as a rope)

**Screenshots**
![image](https://github.com/SBDPlugins/V10Lift/assets/49165798/1ecbd1e8-df8d-4a1a-a061-9099e38f9a2e)

**Spigot version (use /version):**
git-Paper-388 (1.18.2)

**Plugin version (use /v10lift info), NOT LATEST!!!**
v0.7.4.1

**Additional context**
/

**Comment by stijnb1234** [comment]
Why do you want to use trapdoors for the rope?

**Comment by xCraimax** [comment]
I think it's a good addition to my buildings.

**Comment by xCraimax** [comment]
Any updates on this?

**Comment by stijnb1234** [comment]
Will look into this now
