### ISSUE TITLE
[BUG] Inputs not working at all

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#78]
**Describe the bug**
Somehow, all the input buttons are broken on my server, after updating to the newest V10Lift Version. This is a problem, I now have with all lifts (new and old ones).

**To Reproduce**
1. Create Lift
2. Create 2 Floors
3. Create 2 Inputs (for my example I used Stone Buttons & Oak Buttons)
4. Use those buttons

**Expected behavior**
Lift going up/down.

**Screenshots**
/

**Spigot version (use /version):**
v1.20.1 (git-paper 1.20.1)

**Plugin version (use /v10lift info), NOT LATEST!!!**
v0.8

**Additional context**
When upgrading to the newest version i just replaced the .jar file in the plugins folder.

**Comment by stijnb1234** [comment]
Hmm, might be related to the fact something changed it the storage. Could you send your data.db file?

**Comment by xCraimax** [comment]
Sure. Here you go: https://drive.google.com/file/d/13HCQs_Svq_TykxpOJmhtQPbkHtwdU2mR/view?usp=sharing

**Comment by xCraimax** [comment]
Any updates on this?
