### ISSUE TITLE
[FEATURE] Easier Adding of the Elevator Blocks (v10lift build)

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#80]
**Is your feature request related to a problem? Please describe.**
It's quite frustrating to create lifts, with a larger scale, as you need to always add each block seperatly.

**Describe the solution you'd like**
A command to add blocks from a selection (two positions) to a lift.

**Describe alternatives you've considered**
/

**Additional context**
![image](https://github.com/SBDPlugins/V10Lift/assets/49165798/63d01116-0334-4ae6-9146-73f06b5330a7)
The screenshot is for visualization. The red block is the first selected block and the blue block is the 2nd selected block.

**Comment by stijnb1234** [comment]
1. /v10lift create - Select the sign (if outside the cab selection)
2. /v10lift create <Name>
3. Select all the blocks for the cab
4. /v10lift build worldedit - Adds all the selected blocks directly to the elevator
