### ISSUE TITLE
[FEATURE] Redstone Lift-Calling

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#83]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to create complex redstone buildings and mechanics, because V10Lift always requires a user input (button).

**Describe the solution you'd like**
A Block which can be set as an Input (ex. gold_block) → Maybe with a config, where this block can be changed.
Now, this block will call a selected floor, when the block is powered by redstone.

**Describe alternatives you've considered**
/

**Additional context**
Use case example (just imagine, there's a redstone flying machine, which moves the grass - I was too lazy to build one)
![image](https://github.com/SBDPlugins/V10Lift/assets/49165798/f50ae127-b282-4fd8-bcde-eb1117473d20)

**Comment by stijnb1234** [comment]
This should already be possible. Try using /v10lift start <LifeName> <Floor> in a command block. This should queue the floor command (like an input would do) to the floor.

**Comment by xCraimax** [comment]
I assume this would work, but I'd rather use a survival-friendlier solution, as I don't really have access to commandblocks on the server

**Comment by stijnb1234** [comment]
> I assume this would work, but I'd rather use a survival-friendlier solution, as I don't really have access to commandblocks on the server

I see, but assigning a block to it seems too complex for me because it's already possible using something else. I'm sorry, but I'm not going to implement this.
