### ISSUE TITLE
[BUG] Input del not working

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#95]
**Describe the bug**
/v10lift input del is not working. Nothing is happening - no error messages, no chat messages.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an elevator with (for example) 2 floors
2. Create one input per floor
3. try /v10lift input del

**Expected behaviour**
Input being deleted

**Screenshots**

**Spigot version (use /version):**
git-Paper-195

**Plugin version (use /v10lift info), NOT LATEST!!!**
v0.9

**Additional context**
It's possible, that this problem occurs with /v10lift offline del as well.

**Comment by stijnb1234** [comment]
When you run /v10lift input del, you should get a message to right-click the input you want to delete. Then it should delete that input from the elevator. Which part doesn't work?

**Comment by xCraimax** [comment]
I get the message to right-click the input. But nothing happens, when I right-click it.

**Comment by xCraimax** [comment]
Seems working now? Not sure if its a problem with already existing lifts before upgrading. 
But seems to work at least with new lifts.

**Comment by stijnb1234** [comment]
Weird, I've used this feature before and worked fine for me too. Please let me know if you experience this issue again.
