### ISSUE TITLE
[FEATURE] /v10lift door floor selection

### ISSUE THREAD

**Issue by xCraimax** [SBDPlugins/V10Lift#98]
**Is your feature request related to a problem? Please describe.**
For me its frustrating to be required to be on the floor, for which I want to create a door. 

**Describe the solution you'd like**
It would be cool, to be able to use /v10lift door like /v10lift input add.
So like this: /v10lift door [floor]

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by stijnb1234** [comment]
This is already implemented:
/v10lift door - Automatic floor selection, just click on the doors and go.
/v10lift door <Floor> - Click on the doors, they will be bound to the floor you provided.
